/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jNetDev_jND_CaptureThread */

#ifndef _Included_jNetDev_jND_CaptureThread
#define _Included_jNetDev_jND_CaptureThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jNetDev_jND_CaptureThread
 * Method:    capture1
 * Signature: ([BLjNetDev/jND_PacketQueue;)I
 */
JNIEXPORT jint JNICALL Java_jNetDev_jND_1CaptureThread_capture1
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
