/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jNetDev_jND_NICList */

#ifndef _Included_jNetDev_jND_NICList
#define _Included_jNetDev_jND_NICList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_numberOfNICs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jNetDev_jND_1NICList_os_1numberOfNICs
  (JNIEnv *, jclass);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicName
  (JNIEnv *, jclass, jint);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicDescription
  (JNIEnv *, jclass, jint);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicIpaddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicIpaddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicNetmask
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicNetmask
  (JNIEnv *, jclass, jint);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicGateway
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicGateway
  (JNIEnv *, jclass, jint);

/*
 * Class:     jNetDev_jND_NICList
 * Method:    os_nicMacaddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jNetDev_jND_1NICList_os_1nicMacaddress
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
