/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jNetDev_jND_CaptureSession */

#ifndef _Included_jNetDev_jND_CaptureSession
#define _Included_jNetDev_jND_CaptureSession
#ifdef __cplusplus
extern "C" {
#endif
#undef jNetDev_jND_CaptureSession_jND_NONE
#define jNetDev_jND_CaptureSession_jND_NONE 0L
#undef jNetDev_jND_CaptureSession_jND_LIVE
#define jNetDev_jND_CaptureSession_jND_LIVE 1L
#undef jNetDev_jND_CaptureSession_jND_OFFLINE
#define jNetDev_jND_CaptureSession_jND_OFFLINE 2L
/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    openCapture
 * Signature: (ILjava/lang/String;IZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jNetDev_jND_1CaptureSession_openCapture
  (JNIEnv *, jclass, jint, jstring, jint, jboolean, jint);

/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    closeCapture
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_jNetDev_jND_1CaptureSession_closeCapture
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    dumpOpen
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jNetDev_jND_1CaptureSession_dumpOpen
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    dump1
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_jNetDev_jND_1CaptureSession_dump1
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    dumpClose
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jNetDev_jND_1CaptureSession_dumpClose
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jNetDev_jND_CaptureSession
 * Method:    installFilter
 * Signature: ([B[BLjava/lang/String;ZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jNetDev_jND_1CaptureSession_installFilter
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
