/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jNetDev_jND_NIC */

#ifndef _Included_jNetDev_jND_NIC
#define _Included_jNetDev_jND_NIC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jNetDev_jND_NIC
 * Method:    nic_open
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jNetDev_jND_1NIC_nic_1open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jNetDev_jND_NIC
 * Method:    nic_close
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jNetDev_jND_1NIC_nic_1close
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jNetDev_jND_NIC
 * Method:    nic_inject
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jNetDev_jND_1NIC_nic_1inject
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
